title = "Merlins's Cortex"
baseURL = "https://www.merlinscortex.co.uk"
tags = ["science", "data", "web", "technology"]
languageCode = "en-gb"
config = "config.toml"
theme = "osprey"
enableRobotsTXT = true
canonifyURLS = true
googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "Merlin Halliday"
  author = "Merlin Halliday"
  description = "Science and technology enthusiast from the South of England"
  logoBig = "/images/merlins_cortex_logo.png"
  logoSmall = "/images/Merlins Cortex Logo 2-large.png"
  favicon = "/images/favicon.ico"
  opengraphImage = "/images/Merlins Cortex Logo 2-large.png"
  email = "merlin.halliday@myport.ac.uk"
  googleTagManager = ""
  customCSS = false

  # Social media links in footer
  #twitter = "merlinhalliday"
  linkedin = "merlinhalliday"
  github = "merlinhalliday"
  #facebook = ""

  # Copyright and theme author credit in footer
  copyright = false
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = "https://usebasin.com/f/52b94c0c9289"

  # Lazy loading with lazysizes
  lazyloading = true

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Blog"
  url  = "/#blog"
  weight = 2
[[menu.main]]
  name = "CV"
  url  = "/resume"
  weight = 3
